/**
 * Machine-readable block reasons (M10B). Every rejected action returns exactly one
 * of these codes. Doctrine (directive_03): "Every rejected action must return a
 * specific machine-readable block reason."
 */
export enum BlockReason {
  // Foreign keys / references
  INVALID_FOREIGN_KEY = 'INVALID_FOREIGN_KEY',
  ORPHANED_REFERENCE = 'ORPHANED_REFERENCE',

  // Configuration (RC-409/421/425)
  CONFIGURATION_PACKET_MISMATCH = 'CONFIGURATION_PACKET_MISMATCH',
  VEHICLE_IDENTITY_MISMATCH = 'VEHICLE_IDENTITY_MISMATCH',
  CONFIGURATION_CHANGED_AFTER_AUTHORIZATION = 'CONFIGURATION_CHANGED_AFTER_AUTHORIZATION',

  // State machine (RC-408/413)
  ILLEGAL_STATE_TRANSITION = 'ILLEGAL_STATE_TRANSITION',
  EXECUTION_COMPLETION_CANNOT_MUTATE_AUTHORIZATION = 'EXECUTION_COMPLETION_CANNOT_MUTATE_AUTHORIZATION',

  // Authorization activation (RC-386/399/424)
  AUTHORIZATION_EXPIRED = 'AUTHORIZATION_EXPIRED',
  PROCEDURE_APPROVAL_MISSING = 'PROCEDURE_APPROVAL_MISSING',
  PREVIOUS_CELL_SIGNED_PASS_REQUIRED = 'PREVIOUS_CELL_SIGNED_PASS_REQUIRED',
  RUNOUT_NOT_RELEASED = 'RUNOUT_NOT_RELEASED',
  ENVIRONMENTAL_WINDOW_INVALID = 'ENVIRONMENTAL_WINDOW_INVALID',
  THERMAL_STATE_INVALID = 'THERMAL_STATE_INVALID',
  PERSONNEL_NOT_ASSIGNED = 'PERSONNEL_NOT_ASSIGNED',
  CONTAINMENT_NOT_READY = 'CONTAINMENT_NOT_READY',
  MULTIPLE_ACTIVE_TEST_CELLS = 'MULTIPLE_ACTIVE_TEST_CELLS',

  // Authority / numeric threshold (RC-267/300/412)
  INITIAL_TARGET_PROFILE_HAS_NO_MOVEMENT_AUTHORITY = 'INITIAL_TARGET_PROFILE_HAS_NO_MOVEMENT_AUTHORITY',
  INELIGIBLE_AUTHORITY_CLASS = 'INELIGIBLE_AUTHORITY_CLASS',

  // Runout (RC-372/373/383/398/401)
  INSUFFICIENT_TRACK_LENGTH = 'INSUFFICIENT_TRACK_LENGTH',
  INSUFFICIENT_REMAINING_MARGIN = 'INSUFFICIENT_REMAINING_MARGIN',
  OVERLAP_CHECK_FAILED = 'OVERLAP_CHECK_FAILED',
  UNIT_CONSISTENCY_FAILED = 'UNIT_CONSISTENCY_FAILED',
  REQUIRED_COMPONENT_INCOMPLETE = 'REQUIRED_COMPONENT_INCOMPLETE',
  MISSING_RUNOUT_COMPONENT = 'MISSING_RUNOUT_COMPONENT',
  DISTANCE_GEOMETRY_INVALID = 'DISTANCE_GEOMETRY_INVALID',
  OVERLAP_HOST_INVALID = 'OVERLAP_HOST_INVALID',
  TEST_DISTANCE_EXCEEDS_TRACK = 'TEST_DISTANCE_EXCEEDS_TRACK',
  TEST_DISTANCE_NON_POSITIVE = 'TEST_DISTANCE_NON_POSITIVE',
  STEERING_BAND_INVALID = 'STEERING_BAND_INVALID',

  // Instrumentation (RC-391/403)
  INSTRUMENTATION_HEALTH_INVALID = 'INSTRUMENTATION_HEALTH_INVALID',

  // Results / evidence (RC-371/374/410/422)
  RESULT_NOT_SIGNED_PASS = 'RESULT_NOT_SIGNED_PASS',
  COMPLETED_DOES_NOT_CLEAR_GATE = 'COMPLETED_DOES_NOT_CLEAR_GATE',
  SIGNED_EVIDENCE_IS_APPEND_ONLY = 'SIGNED_EVIDENCE_IS_APPEND_ONLY',

  // Faults (RC-380/395/405)
  FAULT_EXECUTED_OUTSIDE_AUTHORIZED_DOMAIN = 'FAULT_EXECUTED_OUTSIDE_AUTHORIZED_DOMAIN',
  FAULT_EXECUTION_UNSIGNED = 'FAULT_EXECUTION_UNSIGNED',
  PAIRED_FAULT_HAZARD_ANALYSIS_MISSING = 'PAIRED_FAULT_HAZARD_ANALYSIS_MISSING',
  PAIRED_FAULT_COMPONENT_REGISTRY_INVALID = 'PAIRED_FAULT_COMPONENT_REGISTRY_INVALID',

  // Duplicate membership (RC-417)
  DUPLICATE_JUNCTION_MEMBERSHIP = 'DUPLICATE_JUNCTION_MEMBERSHIP',
}

/** Thrown by every hard block. Carries the machine-readable reason + detail. */
export class BlockError extends Error {
  readonly reason: BlockReason;
  readonly detail: string;
  constructor(reason: BlockReason, detail = '') {
    super(`BLOCKED: ${reason}${detail ? ` — ${detail}` : ''}`);
    this.name = 'BlockError';
    this.reason = reason;
    this.detail = detail;
  }
}

/** Convenience: assert a condition or throw a BlockError with the given reason. */
export function block(condition: boolean, reason: BlockReason, detail = ''): void {
  if (!condition) throw new BlockError(reason, detail);
}
